project:
  type: website
  output-dir: docs

website:
  title: "Contents"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Overview"
        contents: 
          - index.qmd
      - section: "Scripts"
        contents:
          - calibration.qmd
          - purpleairapi.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

